import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { Items } from "../styles/styled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>HOME</h1>
        <Items>
          <Link href="/protected">Protected</Link>
          <Link href="/login">Login</Link>
        </Items>
      </main>
    </div>
  );
};

export default Home;
