import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import { Items } from "../styles/styled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>PROTECTED</h1>
        <Items>
          <Link href="/"> Home</Link>
          <Link href="/paid"> Paid Content</Link>
        </Items>
      </main>
    </div>
  );
};

export default Home;

const Div = styled.div`
  cursor: pointer;
`;

const WrapForm = styled.div`
  position: relative;
  width: 100%;

  display: flex;
  justify-content: center;

  .ll {
    position: absolute;
    left: 0px;
    width: 100%;
  }
`;
