import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import { Items } from "../styles/styled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>PROTECTED</h1>
        <Items>
          <Link href="/"> Home</Link>
          <Link href="/course"> FREE Content</Link>
          <Link href="/paid"> Paid Content</Link>
        </Items>
      </Main>
    </div>
  );
};

export default Home;

const Main = styled.main`
  min-height: 100vh;
  background-color: white;

  h1 {
    color: black;
  }
`;
